### ISSUE TITLE
Error line 206 : TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by tviguier** [blajoie/vcf2fasta#1]
Hello !
I am interested in your python script,
I tried to realize the example of your github page but at the moment of the result, the linux terminal gives me as error :
"
processing VCF file
	chr 2L
found 980 snps

sorting by position
	chr2L ... 980 snps

processing REF file
	chr2LTraceback (most recent call last):
  File "vcf2fasta.py", line 257, in <module>
    main()
  File "vcf2fasta.py", line 206, in main
    while((current_snp[0] < start) and (len(tmp_pos_list) > 0)):
TypeError: '<' not supported between instances of 'NoneType' and 'int'
"
Do I need to change something in your script to fix this?

Thanks in advance for your answer!
Kind regards

**Comment by dozhun** [comment]
you may use python2 to resolve this error
